puts "WHAT DO YOU WANT YOU HUMAN PIECE OF GARBAGE AND WHY AREN'T YOU WORKING? I HOPE YOU'RE NOT WASITNG MY TIME NOW!!!!1"
response = gets.chomp
puts "WHAT DO YOU MEAN \"#{response.upcase}\"??!! ENOUGH OF YOUR INSOLENCE, YOU'RE FIRED!!! STANLEY, RELEASE THE HOUNDS!"